### PR TITLE
Allow Relay to be used with multirun-parallelisers such as submitit

### PR DESCRIPTION
**Pull request by MylesBartlett**
I have no idea why this works but it does

### CODE REVIEW

**Comment by thomkeh** [comment]
The CI should be split into 4 independent parallel steps:

1. isort
2. black
3. darglint (linter for docstrings)
4. Pytest+type checking – these should go together because they both need all the dependencies installed

**Comment by thomkeh** [comment]
I think you need to run pyright in the poetry env. This might work:

```
poetry shell pyright ranzen
```

**Comment by MylesBartlett** [comment]
I'll give it a go

**Comment by MylesBartlett** [comment]
Alas
```Run poetry shell pyright ranzen
  poetry shell pyright ranzen
  poetry shell pyright tests
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.1[2](https://github.com/predictive-analytics-lab/ranzen/runs/5126180155?check_suite_focus=true#step:9:2)/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/[3](https://github.com/predictive-analytics-lab/ranzen/runs/5126180155?check_suite_focus=true#step:9:3).7.12/x6[4](https://github.com/predictive-analytics-lab/ranzen/runs/5126180155?check_suite_focus=true#step:9:4)/lib
    VENV: .venv/bin/activate
Too many arguments.
Error: Process completed with exit code 1.` ``

**Pull request merged**
